### ISSUE TITLE
LIF: add pages for NounChunk and VerbChunk

### ISSUE THREAD

**Issue by marcverhagen** [lapps/vocabulary-pages#10]

**Comment by ksuderman** [comment]
Do you mean pages on http://vocab.lappsgrid.org or https://lapps.github.io?  There should now be pages http://vocab.lappsgrid.org/NounChunk and http://vocab.lappsgrid.org/VerbChunk available.

**Comment by marcverhagen** [comment]
I meant pages on https://lapps.github.io.
