### ISSUE TITLE
Make views an ordered list

### ISSUE THREAD

**Issue by marcverhagen** [lapps/vocabulary-pages#13]
We decided to interpret views as an ordered list. To do this we need to add something to the context, probably in http://vocab.lappsgrid.org/context-1.0.0.jsonld:

"@context": { 
    "views": { "@container": "@list" } 
}

**Comment by reckart** [comment]
Ah, I guess the views are named through their "id" property.

**Comment by marcverhagen** [comment]
This issue is now added to #23.
