### ISSUE TITLE
PhraseStructure constituents property

### ISSUE THREAD

**Issue by reckart** [lapps/vocabulary-pages#15]
The PhraseStructure constituents property description states

    The set of IDs for the Constituent annotations

Does this refer to the set of all constituents in the sentence or only the top-level constituents (those that do not have parents)?

Why is this a set and not a list?

**Comment by reckart** [comment]
Related to this, is the parent of a top-level constituent the PhraseStructure or is it null?

**Comment by marcverhagen** [comment]
We could make it a list, but then we might have to define what the order means and state something like "the order is determined by depth-first preorder traversal of the tree".

**Comment by marcverhagen** [comment]
And I would say that the parent of a top-level constituent is null, but I do not feel strongly about this.

**Comment by reckart** [comment]
So apparently, the set of constituents only points to the top-level constituents in a sentence (cf. f80137d0b909f3da742aaedafa7f7b036910f67f).

I guess that would mean for most parsers that I know of that there would only be a single entry in the set.

An order could e.g. be defined over the offsets for the top-level constituents.

**Comment by marcverhagen** [comment]
Ah, I see that Nancy changed this to be just the top level constituents. In our implementation of the service wrappers, the value of constituents is actually the list of all constituents in the tree, not just the top-level one. There is a little bit of a disconnect here.

**Comment by marcverhagen** [comment]
One reason this is a set now and not a list is because that way we do not need to define what kind of tree traversal we need to generate the list (pre-order depth first? something else?). We could change this any time of course.
