### ISSUE TITLE
Missing type meta property

### ISSUE THREAD

**Issue by ksuderman** [lapps/vocabulary-pages#22]
_From @marcverhagen on October 29, 2015 2:44_

We use producer, rules and type in the metadata contains section. The first two are defined as metadata properties on Annotation, but type is not defined.

_Copied from original issue: lapps/org.lappsgrid.vocabulary#4_

**Comment by ksuderman** [comment]
_From @nancyide on October 29, 2015 9:25_

what is type?On Oct 29, 2015, at 3:44 AM, marcverhagen <notifications@github.com> wrote:We use producer, rules and type in the metadata contains section. The first two are defined as metadata properties on Annotation, but type is not defined.—Reply to this email directly or view it on GitHub.

**Comment by marcverhagen** [comment]
Good question, the answer to which I have not quite down. The best I can do is from the LIF specifications: "The type key is used to specify what kind of token we are dealing with. It allows several tokenizers to specify the same type, for example if two tokenizers are both implementations of the the OpenNLP tokenization. In the example here the type key has the compact IRI value tokenization:opennlp, where tokenization refers to the tokenization key in the context..."
