### ISSUE TITLE
Phrase structure 

### ISSUE THREAD

**Issue by reckart** [lapps/vocabulary-pages#26]
I am trying to add phrase structure support to the DKPro Core LIF reader/writer (https://github.com/dkpro/dkpro-core/issues/712).

Writing appears to be pretty straightforward.

For reading, I have been looking at the LIF example below (https://lapps.github.io/interchange/phrase_structure.html)

```
{
  "text": "Sue sees herself",
  "views": [
    { "id": "v1",
      "metadata": {
        "contains": {
          "Token": {
            "producer": "edu.brandeis.cs.lappsgrid.opennlp.Tokenizer:n.n.n",
            "type": "tokenizer:opennlp" }}},
      "annotations": [
         { "@type": "Token", "id": "tok0", "start": 0, "end": 3 },
         { "@type": "Token", "id": "tok1", "start": 4, "end": 8 },
         { "@type": "Token", "id": "tok2", "start": 9, "end": 16 } ]},
    { "id": "v2",
      "metadata": {
        "contains": {
          "PhraseStructure": {
            "producer": "edu.brandeis.cs.lappsgrid.SimpleParser:1.0.0",
            "categorySet": "ns/types/PTBcategories",
            "type": "PhraseStructure:SimpleParser" },
          "Constituent": {
            "producer": "edu.brandeis.cs.lappsgrid.SimpleParser:1.0.0",
            "categorySet": "ns/types/PTBcategories",
            "type": "PhraseStructure:SimpleParser" }}},
      "annotations": [
         { "@type": "PhraseStructure",
           "id": "phrase0",
           "start": 0,
           "end": 16,
           "features": {
              "constituents": [ "c0", "c1", "c2", "v1:tok0", "v1:tok1", "v1:tok2" ] }},
         { "@type": "Constituent",
           "label": "S",
           "id": "c0",
           "features": {
             "children": [ "c1", "c2"] } },
         { "@type": "Constituent",
           "label": "NP",
           "id": "c1",
           "features": {
             "children": [ "v1:tok0" ] }},
         { "@type": "Constituent",
           "label": "VP",
           "id": "c2",
           "features": {
             "children": [ "v1:tok1", "v1:tok2" ] }}]}]
}
```

The problem here is, that finding the root in the constituent tree is rather cumbersome, even more so since the `parent` feature (cf. http://vocab.lappsgrid.org/Constituent.html) is not used. But even if it was used, it still would be cumbersome as I would have to scan through all the constituents of the phrase structure to locate the one where the parent is null.

Do you consider the `parent` feature mandatory?

Having a dedicated feature in the phrase structure pointing at the root constituent or defining an order over the items in the `constituents` feature (cf. https://github.com/lapps/vocabulary-pages/issues/15) would also be helpful.

**Comment by marcverhagen** [comment]
I am very sympathetic to making the parent feature mandatory, it is actually an oversight that it is not in the LIF example. And adding a root feature to PhraseStructure would be an improvement too. I am less thrilled about defining an order over the constituents. You cannot get to the tree from the order anyway.

**Comment by marcverhagen** [comment]
The parent feature actually brings up a minor issue. In the example tree we have three Constituents and three Tokens (the three leaf nodes). Since we have the parent feature on Constituents and not on Tokens (where we do not want it) we have a tree where the non-terminals have an explicit parent, but the terminals don't. All elements, constituents and tokens, are listed under the constituents feature of the PhraseStructure object. There is a little bit of cognitive dissonance here.

By the way, I have updated the LIF PhraseStructure example.

**Comment by reckart** [comment]
In DKPro Core, we also have the parent feature on Tokens. I have even already considered to make Token inherit from Constituent, but couldn't convince myself.

**Comment by reckart** [comment]
Using the LAPPS Serialization API and the LAPPS Vocabulary API, it doesn't work properly for me if the atType is just `"@type": "Constituent"`.

I am using code like this:

```
        // Constituents
        view.getAnnotations().stream()
            .filter(a -> Discriminators.Uri.PHRASE_STRUCTURE.equals(a.getAtType()))
            .forEach(...
```

I assume that's how it should be working. But that only works if the atType is set like `"@type": "http://vocab.lappsgrid.org/Constituent",`

So in order to process the PhraseStructure example, I had to modify it:

* use long names in atTypes
* change the `text` item to use atValue and atLanguage and not simply a text value
* I also had to merge the views, but that is rather a problem in my implementation rather than in LAPPS code or examples.

```
{
  "@context" : "http://vocab.lappsgrid.org/context-1.0.0.jsonld",
  "metadata" : { },
  "text" : {
    "@value" : "Sue sees herself",
    "@language" : "en"
  },
  "views": [ {
      "metadata": {
        "contains": {
          "Token": {
            "producer": "edu.brandeis.cs.lappsgrid.opennlp.Tokenizer:n.n.n",
            "type": "tokenizer:opennlp" },
          "PhraseStructure": {
            "producer": "edu.brandeis.cs.lappsgrid.SimpleParser:1.0.0",
            "categorySet": "ns/types/PTBcategories",
            "type": "PhraseStructure:SimpleParser" },
          "Constituent": {
            "producer": "edu.brandeis.cs.lappsgrid.SimpleParser:1.0.0",
            "categorySet": "ns/types/PTBcategories",
            "type": "PhraseStructure:SimpleParser" }}},
      "annotations": [
         { "@type": "http://vocab.lappsgrid.org/Sentence", "id": "sent1", "start": 0, "end": 16 }, 
         { "@type": "http://vocab.lappsgrid.org/Token", "id": "tok0", "start": 0, "end": 3 },
         { "@type": "http://vocab.lappsgrid.org/Token", "id": "tok1", "start": 4, "end": 8 },
         { "@type": "http://vocab.lappsgrid.org/Token", "id": "tok2", "start": 9, "end": 16 },
         { "@type": "http://vocab.lappsgrid.org/PhraseStructure",
           "id": "phrase0",
           "start": 0,
           "end": 16,
           "features": {
              "constituents": [ "c0", "c1", "c2", "tok0", "tok1", "tok2" ] }},
         { "@type": "http://vocab.lappsgrid.org/Constituent",
           "label": "S",
           "id": "c0",
           "features": {
             "children": [ "c1", "c2"] } },
         { "@type": "http://vocab.lappsgrid.org/Constituent",
           "label": "NP",
           "id": "c1",
           "features": {
             "children": [ "tok0" ] }},
         { "@type": "http://vocab.lappsgrid.org/Constituent",
           "label": "VP",
           "id": "c2",
           "features": {
             "children": [ "tok1", "tok2" ] }}]}]
}
```

**Comment by ksuderman** [comment]
The aliasing of "short names" (e.g. Constituent) to the full URI was supposed to be handled by the JSON-LD context, but there are two problems.

1. The current JSON-LD context definition is woefully out of date.  Ideally the context would be updated as the vocabulary is updated.
1. Nothing we have is JSON-LD aware to do the substitution even if we did have an updated context.

Short story: always use the full URI for the @type and the keys in the metadata.contains map.

As for the problem of finding the root constituent of a phrase structure.  I think adding a *root* feature to the phrase structure is the best solution.
