### ISSUE TITLE
Mandatory / optional

### ISSUE THREAD

**Issue by reckart** [lapps/vocabulary-pages#27]
It would be great if the vocabulary could mention which features are considered to be mandatory and which are considered to be optional.

**Comment by marcverhagen** [comment]
For each vocabulary element, add one of two things to lapps.vocab: (1) a "required" attribute that lists the required attributes, or (2) for each attribute, add a "required" attribute with value true or false.

This will also be added as an issue to https://github.com/lappsgrid-incubator/vocabulary-dsl.

**Comment by marcverhagen** [comment]
Here is a list of all properties currently defined (this is for regular properties, not metadata properties). I have added a '+' to those that I suggest are mandatory.

Thing: alternateName
Annotation: +id
Region: targets, start, end
	(note: either targets or start/end are required)
Sentence: sentenceType
VerbChunk: vcType, tense, voice, neg
NamedEntity: category
Date: dateType
Location: locType
Organization: orgType
Person: gender
Token: pos, lemma, tokenType, orth, length, word
Relation: +label
SemanticRole: +head, +argument
Constituent: +parent, +children
Dependency: +governor, +dependent
Coreference: +mentions, representative
PhraseStructure: +constituents, +root
	(note: as of 1/28 root is added in the develop branch only)
DependencyStructure: dependencyType, +dependencies
Document: +id, source, sourceType, +encoding, +language

Motivation. I have added a plus if the element made no sense without it (for example a dependency without a dependent) or if having the property would be of great practical value even if technically it is not needed (for example the root on PhraseStructure). I am on the fence for the representative property on Coreference. I also assume that when a property is required you cannot set its value to null.

**Comment by reckart** [comment]
How do you handle root dependencies? Do they use the same token as governor and dependent (self-looping)?

Why is the source document encoding mandatory? Isn't that a convenience in case you want to seralize in the same encoding instead of a default (i.e. UTF-8).

**Comment by marcverhagen** [comment]
Here is how we handle the root dependency now:

{ "@type": "Dependency",
          "label": "ROOT",
          "id": "dep0",
          "features":	 {
            "governor": null,
            "dependent": "v1:tok1" }}

A strong case can be made to add root as a required attribute to DependencyStructure.

**Comment by marcverhagen** [comment]
I have no strong feelings on making encoding optional.

**Comment by reckart** [comment]
Ok, I was just wondering because the required "governor" is not set in such a case. Btw. it's also a good idea to clearly document how you expect to handle root nodes because wrapped tools sometimes need self-looping and sometimes break on self-looping. For DKPro Core, we decided on self-looping root nodes. Cf. https://github.com/dkpro/dkpro-core/issues/628

**Comment by marcverhagen** [comment]
Right, I was introducing a contradiction when I said mandatory attributes should not have a null value. The semantics of no governor attribute versus a governor attribute with a null value gives me a headache, so maybe I should drop that non-null restriction, or else have an ID or a string for the governor value where the string would be 'ROOT'. I don't think I like self-looping very much, but it would do away with the dual nature of the governor value.

**Comment by reckart** [comment]
To be honest, I'm not sure where the self-looping idea came from - probably from WebAnno where we mark the root of a dependency tree be dragging and arc from a token to itself... but I'm not sure. If there are good reasons against self-looping, I think we would consider to switch our strategy. Right now, I cannot imagine any constellation where a token would legally be its own governor in a dependency tree - but I'm not a linguist.

**Comment by marcverhagen** [comment]
I cannot imagine that constellation either, and I used to be a linguist.

**Comment by reckart** [comment]
Then I guess for the moment we (DKPro Core) are pretty save in using this constellation to mark the root node ;)

**Comment by marcverhagen** [comment]
I added whether properties are required as discussed to the development branch. I think I would like to make "start" and "end" required to, and add a note to the "targets" property that if targets are used then "start" and "end" should be set to null.
