### ISSUE TITLE
Dependency

### ISSUE THREAD

**Issue by ksuderman** [lapps/vocabulary-pages#3]
Add Dependency annotation type as child of Span.

**Comment by ksuderman** [comment]
@marcverhagen @nancyide I am closing issues and came across this... which is not correct is it?  Dependency is a relation and not a type of Span.  At the moment Dependency is a child of Annotation, which I believe is correct.  However, I wanted to double-check before I marked this as "won't fix".

**Comment by nancyide** [comment]
I recall some discussion of that—but Marc would know better.


> On Oct 27, 2015, at 5:31 PM, Keith Suderman <notifications@github.com> wrote:
> 
> @marcverhagen <https://github.com/marcverhagen> @nancyide <https://github.com/nancyide> I am closing issues and came across this... which is not correct is it? Dependency is a relation and not a type of Span. At the moment Dependency is a child of Annotation, which I believe is correct. However, I wanted to double-check before I marked this as "won't fix".
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/lapps/vocabulary-pages/issues/3#issuecomment-151560138>.
> 

-----------------------------------------------------

Nancy Ide
Professor of Computer Science

Department of Computer Science
Vassar College
Poughkeepsie, New York 12604-0520 
USA

tel: (+1 845) 437 5988
fax: (+1 845) 437 7498
email: ide@cs.vassar.edu
http://www.cs.vassar.edu/~ide

-----------------------------------------------------

**Comment by marcverhagen** [comment]
Correct, Dependency is not a subtype of Span. Of course, now that Span has targets we could shove Dependency under Span if we really wanted, but that feels wrong. Maybe we may want to think about having Span and Relation as subtypes of Annotation. And maybe add something like Structure for DependencyStructure and PhraseStructure.

**Comment by ksuderman** [comment]
I like the idea of having Relation and Structure types, but we should open new issues for those.  I am going to go ahead and close this as "won't fix".
