### ISSUE TITLE
Expanding the Date type

### ISSUE THREAD

**Issue by marcverhagen** [lapps/vocabulary-pages#31]
I would like to add "value" as a property to date. And maybe some others as well, given how in the past timex2 and timex3 have dealt with time expressions.

Date is under Named Entity, which makes some sense but which is also a bit uncomfortable. The definition on http://vocab.lappsgrid.org/NamedEntity.html says: "A phrase that clearly identifies an individual from others that have similar attributes, such as the name of a person, organization, location, artifact, etc. as well as temporal expressions", where time expressions seem to be thrown in. Clearly, we have named time expressions. And clearly it is odd calling a time expression an individual.

Having both Date and something like TImex is not good either.

**Comment by reckart** [comment]
Might be an artifact of CoreNLP NER also incorporating SUTime.

**Comment by marcverhagen** [comment]
Definitely, and in that sense having Date as a subtype of NamedEntity made sense.

**Comment by marcverhagen** [comment]
This became moot when NamedEntity was reorganized. Now, we still need at some point a category for dates and or times, but that will be a separate ticket.
