### ISSUE TITLE
SemanticRole vs Dependency

### ISSUE THREAD

**Issue by marcverhagen** [lapps/vocabulary-pages#34]
Under the Relation type we have SemanticRole using "String or URI" for the head and argument properties whereas on Dependency we have "ID" for the governor and dependent properties. I am thinking using "String or URI" was a cut an d paste error, but wanted to check whether there is something else going on.

**Comment by nancyide** [comment]
I would assume the same since it would always be a pointer to an object in the same document (wouldn’t it?). The “String or URI” type is always used when we want to refer to a name or term that is potentially defined elsewhere (which would be the case for role labels here).
