### ISSUE TITLE
Document the process for building new vocabulary pages

### ISSUE THREAD

**Issue by ksuderman** [lapps/vocabulary-pages#36]
The process to generate and deploy the Vocabulary pages needs to be documented and hopefully automated.

**Comment by marcverhagen** [comment]
Process may be changing a little bit over the next week or so:

- Changes to coordinate processing of vocabulary and discriminators input.
- We want to display the version number on vocab.lappsgrid.org.
- We may need a mechanism to deprecate information, for example, on the vocabulary pages we will likely get rid of some main elements (see issue  https://github.com/lapps/vocabulary-pages/issues/39). After deprecation, we would keep the pages up for a while, but not diplay them on the main page anymore.

Here is a diagram of the current process:

![vocab-discriminators](https://cloud.githubusercontent.com/assets/4247673/24772998/6e2030b6-1ae1-11e7-9d36-4e975dd51a1d.jpg)

**Comment by marcverhagen** [comment]
We will not change the implementation now, it is not a high priority, it is a high priority for others to know how to do this:

- update vocabulary
- update discriminators
- push to Maven Central
