### ISSUE TITLE
Add link to JSON-LD / RDF versions for browser users

### ISSUE THREAD

**Issue by reckart** [lapps/vocabulary-pages#38]
For those who like browsers, would be be possible to add links to the JSON-LD and RDF version that work without having to tweak the *Accept* header? ;)

**Comment by ksuderman** [comment]
Any suggestions for the best way to accomplish this?  Should we simply have copies the files with a .txt extension so browsers display the files consistently?

Only two of the file types (RDF and JSONLD) are defined in /etc/mime.types but whether the files are displayed in the browser or downloaded depends on the browser I use, and of course, no two browsers behave the same...

Browser | RDF | OWL | TTL| JSON-LD
----------|-------|------|----|----
Safari | download | display | display | download
Firefox | display | display |display | download
Chrome | download | display | display | display

**Comment by reckart** [comment]
Right now, the content delivered from `http://vocab.lappsgrid.org` seems to be controlled via content negotiation based on the `Accept` header.

If I want the RDF version, I have to enter

```
curl -H "Accept: application/rdf+xml" http://vocab.lappsgrid.org
```

For HTML, I can simply direct the browser to `http://vocab.lappsgrid.org`.

A convenience link on the HTML version to download the OWL/RDF/JSON-LD via a browser would be nice. This link could point to a ZIP file containing the respective other versions. Or it could point to different formats directly. In the latter case, one can always right-click on the links to download them instead of opening them in the browser. But in both cases, the user would not have to resort to using curl. Pity Windows users ;)

**Comment by reckart** [comment]
You know what... forget it! People being able to have a clear advantage! I didn't notice that the formats enumerated on that page **are** actual links to the respective versions... doh!
