### ISSUE TITLE
Adding tagsets

### ISSUE THREAD

**Issue by ksuderman** [lapps/vocabulary-pages#55]
_From @marcverhagen on March 16, 2017 21:23_

We do not have discriminators for tagsets yet. Two ways to do this (both by editing 
[discriminators.config](https://github.com/lappsgrid-incubator/org.lappsgrid.discriminator.dsl/blob/master/src/main/resources/discriminators.config)).

One way is to keep it in house and add a postagset URI to the discriminators:

```groovy
def meta = { "http://vocab.lappsgrid.org/ns/media/meta/$it" }

postagset {
   uri meta('postagset')
   description "POS tagset used." }

brown_tagset { 
   uri meta('tagset#brown')
   description "The Brown tag set, see <SOME_URL>" }
```

This probably requires resolution of issue https://github.com/lapps/vocabulary-pages/issues/39.

The other way is to make the URI for the discriminator the external link:

```groovy
def dkpro = { "https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/tagset-reference.html#$it" }

ptb_tagset {
   uri dkpro('tagset-en-ptb-pos')
   description 'Tag set used in the Penn Tree Bank'
}
```

_Copied from original issue: lappsgrid-incubator/discriminator-dsl#6_

**Comment by ksuderman** [comment]
I think I prefer the first method as it is consistent with what we have so far.  However, the base URI for tag sets should be something like http://vocab.lappsgrid.org/ns/tagsets as http://vocab.lappsgrid.org/ns/media is intended for media types.

```groovy
def tagset = { "http://vocab.lappsgrid.org/ns/tagset/$it" }

'pos-tagset' {
	uri tagset('pos')
	description "Part-Of-Speech tag set used."
}
'brown-tagset' {
	uri tagset('pos#brown')
	description "See <some uri>"
}
'dkpro-tagset-en-ptb-pos' {
	uri tagset('pos#dkpro-en-ptb')
	description 'See https://dkpro.github.io/dkpro-core/releases/1.8.0/docs/tagset-reference.html#tagset-en-ptb-pos'
}
```
The other tag set types would use http://vocab.lappsgrid.org/ns/tagset/ner etc.

**Comment by marcverhagen** [comment]
Yes, http://vocab.lappsgrid.org/ns/media was a typo or me being daft. Question, do we have a namespace for meta data information? If so, then instead of http://vocab.lappsgrid.org/ns/tagsets we could use  http://vocab.lappsgrid.org/ns/meta/tagsets.

The advantage is that there is a clear mapping of meta data properties in the vocab and the metadata content of a LIF object and a location in the discriminator section. The disadvantage is a conflict with the `meta` discriminator which points to http://vocab.lappsgrid.org/ns/meta (which really is http://vocab.lappsgrid.org/ns/meta.html).

**Comment by ksuderman** [comment]
It is unfortunate about the name collision with the http://vocab.lappsgrid.org/ns/meta discriminator, but  that shouldn't prevent us from using a URI like http://vocab.lappsgrid.org/ns/meta/tagsets/pos#ptb as a feature value.  

Another alternative is to use a completely different namespace like http://vocab.lappsgrid.org/meta (no /ns in the path).

**Comment by marcverhagen** [comment]
Yes, as long as there is no need for http://vocab.lappsgrid.org/ns/meta to point at the directory rather than the html file then we should be okay. I guess one option would be to have a special subdirectory of ns/ for things like meta, error, ok etcetera.

**Comment by ksuderman** [comment]
I think we agreed to forego the `/ns/meta` URL and use `http://vocab.lappsgrid.org/ns/tagset/pos` and `http://vocab.lappsgrid.org/ns/tagset/dependency` etc. as the roots for tag set URLs.

**Comment by marcverhagen** [comment]
Yes, we did. I also noticed I self-assigned this and then you end up doing it. Interesting.

**Comment by ksuderman** [comment]
I noticed that you had self-assigned it.  However, I haven't done anything but make comments yet.

**Comment by marcverhagen** [comment]
So why don't I just go ahead and make those changes to the discriminators. You probably have some other coding-related things you could do.
