### ISSUE TITLE
Normalizing named entities

### ISSUE THREAD

**Issue by keighrim** [lapps/vocabulary-pages#69]
This was brought up during today's eager call. 
Some named entities, for example genes and proteins, might need normalization but we're lacking a place to hold such normalized term in the lapps vocabulary.

**Comment by marcverhagen** [comment]
That is not quite the case I just noticed. The Thing annotation type has an alternateName attribute, which we could interpret as a canonical name.

**Comment by keighrim** [comment]
Okay, consider it solved. Closing the issue.
